# Generated by Django 3.1.2 on 2020-10-13 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('image_content', models.ImageField(blank=True, default=None, null=True, upload_to='content/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='my_likes', to=settings.AUTH_USER_MODEL)),
                ('loves', models.ManyToManyField(related_name='my_loves', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='echoes', to='posts.content')),
            ],
        ),
    ]
