# Generated by Django 3.1.2 on 2020-11-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20201128_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image_content',
            field=models.ImageField(blank=True, null=True, upload_to='content/'),
        ),
    ]
